version: '3.7'
services:
  api:
    container_name: api
    hostname: api
    image: edo/bootdocker:1.0
    build:
      context: ../boot-docker
      dockerfile: dockerfile
    ports: 
      - "8082:8080"
    restart: always
  fe:
    container_name: fe
    hostname: fe
    image: edo/hergan-klontong:1.0
    build:
      context: ../Simple-React-Docker
      dockerfile: dockerfile
    ports:
      - "80:80"
    restart: always
